runtime: java11
env: standard
runtime_config:
  jdk: openjdk11


env_variables:
  SPRING_PROFILES_ACTIVE: "production"
  GAE_MEMORY_MB: 8500
  HEAP_SIZE_MB: 8000
handlers:
  - url: /.*
    script: this field is required, but ignored
manual_scaling:
  instances: 1